class GameMode {
  final String id;
  final String name;
  final String description;
  final String icon;
  final bool isPremium;
  final List<String> samplePrompts;
  final String category;
  bool isSelected;

  GameMode({
    required this.id,
    required this.name,
    required this.description,
    required this.icon,
    required this.isPremium,
    required this.samplePrompts,
    required this.category,
    this.isSelected = false,
  });
}

final List<GameMode> gameModes = [
  // Free Modes
  GameMode(
    id: 'getting_started',
    name: 'Getting Started',
    description: 'Perfect for warming up the party with simple drinking rules and challenges.',
    icon: '🎮',
    isPremium: false,
    category: 'Warm-Up (Free)',
    samplePrompts: [
      'Point to who\'s most likely to post a thirst trap and then immediately regret it',
      'Last person to show their most recent awkward selfie drinks',
      'Sip if you\'ve ever pretended to know a TikTok dance you didn\'t',
      'Everyone who\'s ever ghosted someone they were talking to drinks',
      'Sip if you\'ve ever worn the same outfit in multiple Instagram posts',
      'Current player, choose someone to duet on an imaginary TikTok. Everyone votes on best performance, loser drinks!',
      'Who\'s got the weirdest saved photo in their camera roll? Show it or take 2 sips',
      'Person with the lowest battery percentage right now gives out 3 drinks',
      'Everyone who\'s been left on read this week drinks',
      'One word chain: Current player says a word, next player has to say a word that starts with the last letter of previous word. First to mess up drinks!',
      'Sip if you\'ve ever slid into someone\'s DMs and regretted it',
      'Person with the most unread notifications gives out drinks equal to that number (max 5)',
      'Current player, show the most embarrassing photo in your camera roll or take 3 sips',
      'Everyone born in the same season as the current player drinks',
      'Quick! Everyone point to who\'d survive longest in a zombie apocalypse. Person with most fingers pointing at them gives out 3 drinks',
      'Sip if you\'ve ever posted something just to make someone jealous',
      'Last person to show their most recent online purchase drinks',
      'Current player, who in the group would you trust to post on your social media? They take a drink',
      'Who has the most dating app matches? Prove it or everyone assumes you\'re lying and you drink',
      'Sip if you\'ve ever fake laughed at someone\'s joke',
      'Everyone with a cracked phone screen drinks',
      'Current player, trade phones with someone for the next 2 rounds',
      'Sip if you\'ve ever stalked an ex\'s profile',
      'Last person to say "yeet" drinks',
      'Current player, create a new slang word everyone has to use for the next 5 rounds - drink if you forget!',
      'Person with the most followers on any platform gives out 3 drinks',
      'Waterfall: Everyone drinks until the person to their right stops',
      'Sip if you\'ve ever posted a story hoping someone specific would see it',
      'Current player, caption the last photo taken by the person to your left. If they laugh, they drink',
      'Everyone wearing something with a logo drinks',
      'Current player, do your best impression of someone famous or take 2 drinks',
      'Sip if you\'ve ever accidentally liked an old photo while stalking someone',
      'Person who last posted on social media gives out 2 drinks',
      'Current player, create a 5-second handshake with the person to your right',
      'Quick! Everyone post the same random emoji in the group chat. Last person to do it drinks',
      'Sip if you\'ve ever used a filter to completely change how you look',
      'Everyone who has sent a risky text today drinks',
      'Current player, show your top 3 most-used emojis. Group decides if they\'re basic (drink if yes)',
      'Sip if you\'ve ever pretended to be busy when you weren\'t',
      'Current player, choose a song. Everyone has to vibe to it or drink',
      'Last person to show their most embarrassing saved meme drinks',
      'Sip if you\'ve ever Googled yourself',
      'Current player, choose someone to have a staring contest with. Loser drinks!',
      'Person with the most apps on their phone gives out drinks equal to the number of home screens they have',
      'Sip if you\'ve ever sent a screenshot to the wrong person',
      'Current player, do your best TikTok dance or take 3 sips',
      'Everyone who has ghosted someone drinks',
      'Last person to dap up everyone in the room drinks',
      'Current player, record a 5-second voice message to send to your most recent match or take 3 drinks',
      'Sip if you\'ve ever posted a thirst trap',
      'Everyone take a selfie right now. Person with the worst angle drinks',
      'Current player, let the group pick a new profile pic from your camera roll or take 2 drinks',
      'Sip if you\'ve ever texted "wyd" just to start a conversation',
      'Last person to show their Spotify wrapped or most played song drinks',
      'Current player, choose someone to arm wrestle. Loser drinks!',
      'Person with the most dating apps gives out 3 drinks',
      'Everyone with a phone case drinks',
      'Current player, who in the group would you trust with your darkest secret? They drink',
      'Sip if you\'ve ever accidentally called someone you were just stalking',
      'Last person to show their screen time report drinks',
      'Current player, let someone post a story on your account or take 3 drinks',
      'Sip if you\'ve ever taken a mirror selfie today',
      'Quick! Everyone put their phone in the middle. First notification gets a drink',
      'Current player, let the group see your camera roll or take 2 drinks',
      'Person who last posted a story gives out 2 drinks',
      'Sip if you\'ve ever used the same profile pic for more than 6 months',
      'Current player, show the last text you sent or take 2 drinks',
      'Last person to name a trending song drinks',
      'Everyone wearing something they bought in the last month drinks',
      'Current player, who in this group has the best style? They give out 2 drinks',
      'Sip if you\'ve ever pretended to be into something just to impress someone',
      'Person with the longest snap streak gives out drinks equal to days/100 (max 5)',
      'Current player, let someone scroll through your following list for 10 seconds or take 3 drinks',
      'Everyone who posted today drinks',
      'Quick! Everyone show their lock screen. Most basic one drinks',
      'Current player, show your most recent emoji use or take 2 drinks',
      'Sip if you\'ve ever rewatched your own stories multiple times',
      'Last person to show the last song they listened to drinks',
      'Current player, show your most recent Google search or take 2 drinks',
      'Person with the most folders on their home screen gives out 2 drinks',
      'Everyone with an unread text drinks',
      'Current player, let someone see your screen time report or take 3 drinks',
      'Sip if you\'ve ever posted a selfie and deleted it because it didn\'t get enough likes',
      'Last person to show their most recent saved TikTok drinks',
      'Everyone take a selfie together. Whoever blinks drinks',
      'Current player, show your most used app or take 2 drinks',
      'Person who last opened Instagram gives out 2 drinks',
      'Sip if you\'ve ever sent a "hey" text just to get attention',
      'Current player, let someone send a text from your phone or take 3 drinks',
      'Quick! Everyone point to the person with the best Instagram aesthetic. They give out 2 drinks',
      'Last person to copy the current player\'s pose drinks',
      'Sip if you\'ve ever untagged yourself from a photo',
      'Current player, create a pose everyone must copy. Last to do it drinks!',
      'Person with the most notifications right now gives out that many drinks (max 5)',
      'Everyone who\'s been in a TikTok drinks',
      'Current player, who in the group would go viral first? They give out 2 drinks',
      'Sip if you\'ve ever accidentally liked a post from years ago',
      'Last person to pull up their BeReal drinks',
      'Current player, let someone add a song to your playlist or take 2 drinks',
      'Person with the most alarms set gives out 3 drinks',
      'Sip if you\'ve ever posted cryptic song lyrics after a breakup',
      'Everyone with a custom phone background drinks',
      'Current player, let someone choose your next dating app profile pic or take 3 drinks',
      'Last person to show their photo editing apps drinks',
      'Quick! Everyone show their most used GIF. Group votes on best one, loser drinks',
      'Sip if you\'ve ever googled someone before meeting them',
      'Person who last checked their ex\'s profile gives out 2 drinks',
      'Current player, let someone see your screen time or take 2 drinks',
      'Everyone with more than 10 unopened emails drinks',
      'Last person to caption the current scene like a TikTok drinks',
      'Current player, let someone choose your next Instagram caption or take 3 drinks',
      'Sip if you\'ve ever posted something because someone else did',
      'Person with the most drafts in their notes app gives out 2 drinks',
      'Everyone with dark mode enabled drinks',
      'Current player, let someone choose a new social media profile picture for you or take 3 drinks',
      'Last person to do the viral move of the moment drinks',
      'Sip if you\'ve ever pretended to be in a relationship for social media',
      'Everyone who\'s used a dating app this week drinks',
      'Current player, create a challenge for the group. Everyone who fails drinks!',
      'Person who last sent a voice note gives out 2 drinks',
      'Quick! Everyone point to who has the most main character energy. They choose who drinks',
      'Current player, let someone post on your Close Friends story or take 3 drinks',
      'Sip if you\'ve ever canceled plans to stay in and watch TikToks',
      'Everyone with their brightness above 50% drinks',
      'Last person to show their most embarrassing playlist drinks',
      'Current player, who in the group posts the best stories? They give out 2 drinks',
      'Sip if you\'ve ever screenshot someone\'s story',
      'Person who last checked their screen time gives out drinks equal to hours spent (max 5)',
      'Current player, let someone pick a new lock screen for you or take 3 drinks',
      'Everyone who has sent a streak today drinks',
      'Last person to show their most recent saved post drinks',
      'Current player, create a new slang word everyone must use for the next 5 rounds',
      'Sip if you\'ve ever posted a story just to get someone\'s attention',
      'Person with the most tabs open in their browser gives out 2 drinks',
      'Everyone who has a TikTok account drinks',
      'Current player, let someone scroll through your liked videos or take 3 drinks',
      'Last person to show their top artists drinks',
      'Quick! Everyone point to who would be most likely to become an influencer. They give out 3 drinks',
      'Sip if you\'ve ever used social media while on the toilet',
      'Person who last posted a selfie gives out 2 drinks',
      'Current player, let someone see your recently deleted photos or take 3 drinks',
      'Everyone with location services on drinks',
      'Last person to show their most recent sushi order drinks',
      'Current player, who in the group would you trust to take your next profile pic? They drink',
      'Sip if you\'ve ever unfollowed someone who unfollowed you',
      'Person with the lowest battery percentage gives out that percentage in drinks (max 5)',
      'Everyone with a case on their phone drinks',
      'Current player, let someone choose your next dating app bio or take 3 drinks',
      'Last person to do jazz hands drinks',
      'Sip if you\'ve ever called someone just to immediately hang up',
      'Person who last posted a story gives out 2 drinks',
      'Current player, let someone scroll through your Spotify playlists or take 2 drinks',
      'Everyone with a cracked screen drinks',
      'Quick! Everyone point to who would survive a horror movie. They choose who drinks',
      'Sip if you\'ve ever posted something at a specific time for maximum likes',
      'Last person to add a song to their playlist drinks',
      'Current player, let someone see your following list or take 2 drinks',
      'Person with the longest notes app gives out 3 drinks',
      'Everyone with an app they\'ve never used drinks',
      'Current player, who in the group has the best camera roll? They give out 2 drinks',
      'Sip if you\'ve ever posted a story just to show off',
      'Last person to show their most recent DM drinks',
      'Person who most recently used social media gives out 2 drinks',
      'Current player, let someone pick a song that you have to use as your next story soundtrack or take 3 drinks',
      'Everyone with battery saving mode on drinks',
      'Quick! Everyone point to who would win in a dance battle. They choose who drinks',
      'Sip if you\'ve ever googled your crush',
      'Last person to show their most recent screenshot drinks',
      'Current player, let someone pick a filter you must use for your next post or take 3 drinks',
      'Person with the most unread messages gives out that many drinks (max 5)',
      'Everyone with auto-brightness on drinks',
      'Current player, who in the group has the best style? They give out 2 drinks',
      'Sip if you\'ve ever rewatched your own posts',
      'Last person to show their app layout drinks',
      'Quick! Everyone point to who would be most likely to become famous. They give out 3 drinks',
      'Current player, let someone pick a new bio for one of your socials or take 3 drinks',
      'Person who most recently edited a caption gives out 2 drinks',
      'Everyone with a custom ringtone drinks',
      'Sip if you\'ve ever posted something passive-aggressive',
      'Last person to show their camera roll drinks',
      'Current player, let someone choose who you have to duet with on your next TikTok or take 3 drinks',
      'Person who last unfollowed someone gives out 2 drinks',
      'Everyone with a dating app notification drinks',
      'Quick! Everyone point to who has the best taste in music. They choose who drinks',
      'Sip if you\'ve ever created a fake account to stalk someone',
      'Last person to show their most played song this week drinks',
      'Current player, let someone add a photo to your drafts or take 3 drinks',
      'Person with the most Snapchat streaks gives out 3 drinks',
      'Everyone with more than 5 social media apps drinks',
      'Current player, who in the group would you trust to manage your social media for a day? They give out 2 drinks',
      'Sip if you\'ve ever posted something to make an ex jealous',
      'Last person to show their pinned messages drinks',
      'Quick! Everyone point to who would be most likely to go viral. They choose who drinks',
      'Current player, let someone post on your BeReal or take 3 drinks',
      'Person who last ghosted someone gives out 3 drinks',
      'Everyone with Do Not Disturb mode on drinks',
      'Sip if you\'ve ever texted the wrong person on purpose',
      'Last person to show their most recently used stickers drinks',
      'Current player, let someone search something on your phone or take 3 drinks',
      'Person with the most screenshots gives out 3 drinks',
    ],
  ),
  GameMode(
    id: 'getting_tipsy',
    name: 'Getting Tipsy',
    description: 'Step it up a notch with more challenging and entertaining drinking tasks.',
    icon: '🍻',
    isPremium: false,
    category: 'Warm-Up (Free)',
    samplePrompts: [
      'Point to the person you think is most likely to get canceled - they drink!',
      'Vibe check! Anyone who can\'t name the current #1 song on TikTok drinks',
      'Current player, give out drinks equal to how many dating apps you have',
      'Group vote: most chaotic person in the room gives out 3 drinks',
      'Sip if you\'ve ever pretended to be busy to avoid someone',
      'Current player and their pick must freestyle rap battle. Group votes on winner, loser drinks!',
      'Last person to show their most embarrassing photo in their camera roll takes 3 sips',
      '"Finish the lyric" challenge - current player starts a popular song, next person continues or drinks',
      'Truth: Person who\'s gone the longest without posting on social media gives out 2 drinks',
      'Everyone who\'s left someone on read today drinks',
      'Current player, name your toxic trait or take 2 drinks',
      'Person with the most dating app matches gives out drinks equal to their body count (max 5)',
      'Quick! Everyone strike a pose - most awkward pose (group decides) drinks double',
      'Sip if you\'ve ever unmatched someone right after matching',
      'Current player, tell us your biggest red flag or take 2 drinks',
      'Everyone with a situationship drinks',
      'Truth time: Current player, who in this room would you least want to be stranded with? They drink',
      'Sip if you\'ve ever written a draft text and never sent it',
      'Current player, admit something you\'ve never told anyone or take 3 drinks',
      'Last person to successfully do the latest TikTok dance drinks',
      'Everyone with over 1,000 unread emails drinks',
      'Current player, show us your most sus saved photo or take 3 drinks',
      'Waterfall starting with the person who most recently got ghosted',
      'Sip if you\'ve ever screenshots someone\'s story to talk about it',
      'Truth: Current player, rate everyone\'s outfit 1-10. Anyone below 7 drinks',
      'Last person to finish the sentence "I\'ve never told anyone but..." drinks',
      'Everyone who\'s cried over someone who wasn\'t worth it drinks',
      'Current player, roast someone in the room (respectfully). If they laugh, they drink',
      'Quick! Everyone say their best pickup line. Worst one (group decides) drinks',
      'Sip if you\'ve ever sent a risky text and immediately regretted it',
      'Current player, show the most embarrassing thing in your search history or take 3 drinks',
      'Person with the most notifications right now gives out that many drinks (max 5)',
      'Everyone who\'s ever been in a talking stage for over 3 months drinks',
      'Current player, who in this room would you trust with your password? They drink',
      'Truth: Current player, what\'s your most toxic trait? Group votes if it\'s accurate - drink if yes',
      'Sip if you\'ve ever fake laughed at someone\'s joke',
      'Last person to name 5 red flags drinks',
      'Current player, give your honest impression of each person when you first met them. Anyone offended drinks',
      'Everyone who\'s ever been the toxic one in a relationship drinks',
      'Quick! Everyone point to who\'s most likely to become famous - they give out 3 drinks',
      'Current player, what\'s your most embarrassing drunk story? If you don\'t share, take 3 drinks',
      'Sip if you\'ve ever stalked someone\'s entire Instagram',
      'Person who most recently got left on read gives out 2 drinks',
      'Everyone who\'s sent a risky text today drinks',
      'Current player, who in this room has the worst taste in partners? They drink',
      'Truth: Current player, what\'s a lie you\'ve told recently? If you don\'t share, take 3 drinks',
      'Last person to show their most recent dating app conversation drinks',
      'Sip if you\'ve ever posted a thirst trap after a breakup',
      'Current player, give an impression of someone in the room. If they can\'t guess who, everyone drinks',
      'Everyone who\'s ever been caught in a lie drinks',
      'Quick! Everyone point to who gives the best advice - they give out 3 drinks',
      'Current player, choose someone to play "two truths and a lie" with. If they guess right, you drink',
      'Sip if you\'ve ever sent a screenshot to the wrong person',
      'Last person to name 3 icks drinks',
      'Everyone who\'s ever been in a situationship drinks',
      'Current player, who in this room would you trust with your life? They give out 3 drinks',
      'Truth: Current player, what\'s the most embarrassing song in your playlist? If you don\'t share, take 3 drinks',
      'Sip if you\'ve ever drunk texted an ex',
      'Person who most recently got curved gives out 2 drinks',
      'Everyone with more than 3 dating apps drinks',
      'Current player, show the last person you stalked on social media or take 3 drinks',
      'Quick! Everyone point to who\'s most likely to become a CEO - they give out 3 drinks',
      'Last person to successfully do a TikTok transition drinks',
      'Sip if you\'ve ever used the "my friend took my phone" excuse',
      'Current player, who in this room would you never date? They drink',
      'Everyone who\'s ever been in a love triangle drinks',
      'Truth: Current player, what\'s your biggest turn-off? Group votes if it\'s valid - drink if no',
      'Last person to show their most embarrassing playlist drinks',
      'Current player, show us your hidden talents or take 3 drinks',
      'Sip if you\'ve ever screenshot a dating profile to share with friends',
      'Person who most recently got a new match gives out 2 drinks',
      'Everyone who\'s ever been called out for being toxic drinks',
      'Quick! Everyone point to who\'s most likely to marry rich - they give out 3 drinks',
      'Current player, show the last DM you sent or take 3 drinks',
      'Sip if you\'ve ever posted subliminal messages on your story',
      'Last person to successfully name 5 green flags drinks',
      'Everyone who\'s ever been the rebound drinks',
      'Current player, who in this room would you trust with your secrets? They give out 2 drinks',
      'Truth: Current player, what\'s the wildest thing you\'ve done this month? If you don\'t share, take 3 drinks',
      'Quick! Everyone point to who\'s most likely to ghost someone - they give out 3 drinks',
      'Sip if you\'ve ever pretended to be someone\'s partner to get them out of an awkward situation',
      'Current player, choose someone to have a staring contest with. Loser drinks!',
      'Everyone who\'s ever slid into DMs drinks',
      'Last person to successfully name 5 things they\'re looking for in a partner drinks',
      'Current player, let someone see your screen time or take 3 drinks',
      'Truth: Current player, what\'s the most embarrassing thing in your camera roll? If you don\'t share, take 3 drinks',
      'Sip if you\'ve ever sent mixed signals',
      'Person who most recently added someone on social media gives out 2 drinks',
      'Everyone who\'s ever friendzoned someone drinks',
      'Quick! Everyone point to who\'s most likely to have a secret - they give out 3 drinks',
      'Current player, show your most embarrassing selfie or take 3 drinks',
      'Last person to successfully name 5 things they\'d never compromise on in a relationship drinks',
      'Sip if you\'ve ever unmatched someone immediately after matching',
      'Current player, who in this room would you trust to set you up on a date? They give out 2 drinks',
      'Everyone who\'s ever been caught lying drinks',
      'Truth: Current player, what\'s your biggest flex? Group votes if it\'s impressive - drink if no',
      'Quick! Everyone point to who\'s most likely to become an influencer - they give out 3 drinks',
      'Sip if you\'ve ever gone through someone\'s following list',
      'Last person to successfully name 5 dealbreakers drinks',
      'Current player, show your most recent screenshot or take 3 drinks',
      'Everyone who\'s ever been in a situation-ship drinks',
      'Truth: Current player, what\'s the most embarrassing thing you\'ve done to impress someone? If you don\'t share, take 3 drinks',
      'Quick! Everyone point to who\'s most likely to be famous - they give out 3 drinks',
      'Sip if you\'ve ever lied about your body count',
      'Current player, show your most recent saved TikTok or take 3 drinks',
      'Everyone who\'s ever been called clingy drinks',
      'Last person to successfully name 5 toxic traits drinks',
      'Current player, who in this room would you never hook up with? They drink',
      'Truth: Current player, what\'s the most controversial opinion you've ever had? Group votes if it\'s valid - drink if no',
      'Sip if you\'ve ever posted something to make someone jealous',
      'Person who most recently got a new follower gives out 2 drinks',
      'Everyone who\'s ever been curved drinks',
      'Quick! Everyone point to who\'s most likely to become a millionaire - they give out 3 drinks',
      'Current player, show your most recent search history or take 3 drinks',
      'Last person to successfully name 5 red flags they\'ve ignored drinks',
      'Sip if you\'ve ever sent a risky text while drunk',
      'Current player, who in this room has the best style? They give out 2 drinks',
      'Everyone who\'s ever been called out for being fake drinks',
      'Truth: Current player, what\'s the most embarrassing thing you\'ve done for attention? If you don\'t share, take 3 drinks',
      'Quick! Everyone point to who\'s most likely to be in a scandal - they give out 3 drinks',
      'Sip if you\'ve ever pretended to be busy when you weren\'t',
      'Current player, show your most embarrassing photo or take 3 drinks',
      'Everyone who\'s ever been called toxic drinks',
      'Last person to successfully name 5 green flags they look for drinks',
      'Current player, who in this room would you trust with your phone? They give out 2 drinks',
      'Truth: Current player, what\'s the worst lie you\'ve ever told? If you don\'t share, take 3 drinks',
      'Sip if you\'ve ever read a message and not responded for days',
      'Person who most recently posted a selfie gives out 2 drinks',
      'Everyone who\'s ever been left on read drinks',
      'Quick! Everyone point to who\'s most likely to become president - they give out 3 drinks',
      'Current player, show your most embarrassing DM or take 3 drinks',
      'Last person to successfully name 5 icks they have drinks',
      'Sip if you\'ve ever ghosted someone',
      'Current player, who in this room would you trust with your secret? They give out 2 drinks',
      'Everyone who\'s ever been called out for being dramatic drinks',
      'Truth: Current player, what\'s the most embarrassing thing in your search history? If you don\'t share, take 3 drinks',
      'Quick! Everyone point to who\'s most likely to get rich quick - they give out 3 drinks',
      'Sip if you\'ve ever lied about where you were',
      'Current player, show your most recent liked post or take 3 drinks',
      'Everyone who\'s ever been called out for being petty drinks',
      'Last person to successfully name 5 things they look for in a potential partner drinks',
      'Current player, who in this room has the best taste in music? They give out 2 drinks',
      'Truth: Current player, what\'s the most embarrassing thing you\'ve done while drunk? If you don\'t share, take 3 drinks',
      'Sip if you\'ve ever sent a drunk text you regretted',
      'Person who most recently got ghosted gives out 2 drinks',
      'Everyone who\'s ever been called out for being jealous drinks',
      'Quick! Everyone point to who\'s most likely to become famous on TikTok - they give out 3 drinks',
      'Current player, show your most embarrassing photo on social media or take 3 drinks',
      'Last person to successfully name 5 things they\'ve lied about drinks',
      'Sip if you\'ve ever lied about your age',
      'Current player, who in this room would you trust with your crush\'s name? They give out 2 drinks',
      'Everyone who\'s ever been called out for being sensitive drinks',
      'Truth: Current player, what\'s the most embarrassing thing you\'ve done for love? If you don\'t share, take 3 drinks',
      'Quick! Everyone point to who\'s most likely to become a reality TV star - they give out 3 drinks',
      'Sip if you\'ve ever lied about your relationship status',
      'Current player, show your most embarrassing childhood photo or take 3 drinks',
      'Everyone who\'s ever been called out for being immature drinks',
      'Last person to successfully name 5 things they\'ve done that they regret drinks',
      'Current player, who in this room has the best sense of humor? They give out 2 drinks',
      'Truth: Current player, what\'s the most embarrassing thing you\'ve done to get someone\'s attention? If you don\'t share, take 3 drinks',
      'Sip if you\'ve ever stalked someone\'s new partner',
      'Person who most recently changed their relationship status gives out 2 drinks',
      'Everyone who\'s ever been called out for being controlling drinks',
      'Quick! Everyone point to who\'s most likely to become a social media star - they give out 3 drinks',
      'Current player, show your most embarrassing dating app profile or take 3 drinks',
      'Last person to successfully name 5 things they\'ve lied about on a date drinks',
      'Sip if you\'ve ever lied about your job',
      'Current player, who in this room has the best taste in partners? They give out 2 drinks',
      'Everyone who\'s ever been called out for being clingy drinks',
      'Truth: Current player, what\'s the most embarrassing thing you\'ve done to get someone\'s number? If you don\'t share, take 3 drinks',
      'Quick! Everyone point to who\'s most likely to become a professional athlete - they give out 3 drinks',
      'Sip if you\'ve ever lied about your interests to impress someone',
      'Current player, show your most embarrassing text message or take 3 drinks',
      'Everyone who\'s ever been called out for being narcissistic drinks',
      'Last person to successfully name 5 things they\'ve done to impress someone drinks',
      'Current player, who in this room has the best taste in movies? They give out 2 drinks',
      'Truth: Current player, what\'s the most embarrassing thing you\'ve done in public? If you don\'t share, take 3 drinks',
      'Sip if you\'ve ever lied about your relationship history',
      'Person who most recently went on a date gives out 2 drinks',
      'Everyone who\'s ever been called out for being insecure drinks',
      'Quick! Everyone point to who\'s most likely to become a CEO - they give out 3 drinks',
      'Current player, show your most embarrassing photo with an ex or take 3 drinks',
      'Last person to successfully name 5 things they look for in a relationship drinks',
      'Sip if you\'ve ever lied about being busy',
      'Current player, who in this room has the best fashion sense? They give out 2 drinks',
      'Everyone who\'s ever been called out for being possessive drinks',
      'Truth: Current player, what\'s the most embarrassing thing you\'ve done on a date? If you don\'t share, take 3 drinks',
      'Quick! Everyone point to who\'s most likely to become a model - they give out 3 drinks',
      'Sip if you\'ve ever lied about your feelings',
      'Current player, show your most embarrassing drunk photo or take 3 drinks',
      'Everyone who\'s ever been caught in a lie on social media drinks',
      'Last person to successfully name 5 things they\'ve done to get over an ex drinks',
      'Current player, who in this room has the best smile? They give out 2 drinks',
      'Truth: Current player, what\'s the most embarrassing thing you\'ve said to a crush? If you don\'t share, take 3 drinks',
      'Sip if you\'ve ever lied about where you were going',
      'Person who most recently changed their profile picture gives out 2 drinks',
      'Everyone who\'s ever been called out for being manipulative drinks',
      'Quick! Everyone point to who\'s most likely to become a celebrity - they give out 3 drinks',
      'Current player, show your most embarrassing note in your notes app or take 3 drinks',
      'Last person to successfully name 5 things they regret posting on social media drinks'
    ],
  ),

  // Premium Modes
  GameMode(
  id: 'never_have_i_ever',
  name: 'Never Have I Ever',
  description: 'Classic drinking game with a Gen Z twist! Take a sip if you\'ve done it, point at who you think has.',
  icon: '🤔',
  isPremium: true,
  category: 'Classics',
  samplePrompts: [
    // Digital & Social Media Life
    'Never have I ever ghosted someone I was dating',
    'Never have I ever accidentally liked a really old post while stalking someone',
    'Never have I ever sent a text to the wrong person that got me in trouble',
    'Never have I ever posted something just for the likes/attention',
    'Never have I ever gone viral on any social platform',
    'Never have I ever had a finsta (fake Instagram account)',
    'Never have I ever stayed up all night binge-watching a show',
    'Never have I ever pretended to be on my phone to avoid talking to someone',
    'Never have I ever unfollowed someone because I was jealous',
    'Never have I ever used someone else\'s streaming password without them knowing',
    'Never have I ever lied about my age online',
    'Never have I ever posted a thirst trap',
    'Never have I ever used a dating app for free food',
    'Never have I ever forgotten to mute myself on a Zoom call',
    'Never have I ever accidentally shared my screen showing something embarrassing',
    'Never have I ever been blocked on social media',
    'Never have I ever slid into a celebrity\'s DMs',
    'Never have I ever faked my location on social media',
    'Never have I ever taken a "sick day" to play video games or binge Netflix',
    'Never have I ever bought followers or likes for my social media',

    // School & Work Life
    'Never have I ever cheated on an exam',
    'Never have I ever fallen asleep during class or a work meeting',
    'Never have I ever submitted an assignment one minute before the deadline',
    'Never have I ever used AI to write my essay or do my homework',
    'Never have I ever had a job I absolutely hated',
    'Never have I ever quit a job without giving notice',
    'Never have I ever worked in retail during Black Friday',
    'Never have I ever lied on my resume',
    'Never have I ever called in sick when I was actually hungover',
    'Never have I ever shown up to class still drunk from the night before',
    'Never have I ever completely forgotten about an assignment until it was too late',
    'Never have I ever had a crush on a teacher or professor',
    'Never have I ever been fired from a job',
    'Never have I ever bombed a job interview',
    'Never have I ever been caught cheating on a test',
    'Never have I ever had a side hustle',
    'Never have I ever cried because of a bad grade',
    'Never have I ever accidentally sent a professor or boss a casual/inappropriate email',
    'Never have I ever completely forgotten what I was studying for after a test',
    'Never have I ever pulled an all-nighter to finish an assignment',

    // Party & Social Life
    'Never have I ever crashed a party I wasn\'t invited to',
    'Never have I ever pretended to know the lyrics to a song everyone else knew',
    'Never have I ever blacked out from drinking',
    'Never have I ever been kicked out of a bar or club',
    'Never have I ever made out with someone at a party just because I was bored',
    'Never have I ever sent a drunk text I seriously regretted',
    'Never have I ever gone home with someone I just met',
    'Never have I ever had a hangover that lasted more than one day',
    'Never have I ever thrown up in an Uber/Lyft',
    'Never have I ever been the designated driver and secretly had drinks anyway',
    'Never have I ever pregamed so hard I didn\'t make it to the main event',
    'Never have I ever stolen alcohol from my parents or roommates',
    'Never have I ever taken drugs at a music festival',
    'Never have I ever been caught sneaking out/in by my parents',
    'Never have I ever lied about where I was going for the night',
    'Never have I ever gotten a tattoo I regret',
    'Never have I ever had to be carried home by friends',
    'Never have I ever woken up with no idea how I got home',
    'Never have I ever been to a rave',
    'Never have I ever been turned away at a club for being too drunk',

    // Relationship & Dating Life
    'Never have I ever dated two people at the same time without them knowing',
    'Never have I ever stalked an ex\'s social media right after a breakup',
    'Never have I ever gone through someone\'s phone without permission',
    'Never have I ever had a crush on a friend\'s significant other',
    'Never have I ever kissed my best friend',
    'Never have I ever lied about being single',
    'Never have I ever gotten back with an ex more than twice',
    'Never have I ever dated someone my friends hated',
    'Never have I ever sent nudes to the wrong person',
    'Never have I ever hidden someone I was dating from my parents or friends',
    'Never have I ever pretended to like something just to impress someone I was into',
    'Never have I ever dated someone primarily because they were rich or popular',
    'Never have I ever faked an accent to impress someone',
    'Never have I ever used the "my friend thinks you\'re cute" line when I was actually talking about myself',
    'Never have I ever pretended not to care when I actually did',
    'Never have I ever gotten a hickey I couldn\'t hide',
    'Never have I ever kept talking to someone just because I was bored',
    'Never have I ever dumped someone via text',
    'Never have I ever faked being interested in someone\'s hobby just to spend time with them',
    'Never have I ever had a rebound relationship',

    // Food & Lifestyle
    'Never have I ever eaten an entire pizza by myself in one sitting',
    'Never have I ever pretended to like a food just to seem cultured',
    'Never have I ever gone vegan/vegetarian and quit after less than a month',
    'Never have I ever taken food from a roommate without asking',
    'Never have I ever ordered food delivery when I was too lazy to go outside',
    'Never have I ever spent over $50 on a single meal',
    'Never have I ever used my parents\' credit card without permission',
    'Never have I ever gone into credit card debt for something unnecessary',
    'Never have I ever pretended to be rich when I was broke',
    'Never have I ever eaten something directly out of the trash',
    'Never have I ever spent money I was supposed to use for bills on something fun instead',
    'Never have I ever stolen something from a store',
    'Never have I ever snuck food into a movie theater',
    'Never have I ever gone commando because I ran out of clean underwear',
    'Never have I ever worn the same clothes for more than three days straight',
    'Never have I ever lied about my height on a dating profile',
    'Never have I ever used fake ID',
    'Never have I ever gone more than three days without showering',
    'Never have I ever borrowed something and never returned it',
    'Never have I ever pretended to be someone I\'m not to impress others',

    // Interactive Prompts
    'Never have I ever had a crush on someone in this room - if yes, everyone gets to guess who',
    'Never have I ever talked behind the back of someone in this room - if yes, take an extra drink',
    'Never have I ever been jealous of someone in this room - point to who it was!',
    'Never have I ever seen someone in this room embarrass themselves and didn\'t tell them',
    'Never have I ever lied to someone in this room - if yes, everyone gets to ask you one question',
    'Never have I ever snooped through the phone of someone in this room',
    'Never have I ever thought someone in this room was being fake',
    'Never have I ever had a dream about someone in this room - if yes, you must give a hint about who',
    'Never have I ever secretly disliked something that someone in this room recommended',
    'Never have I ever avoided plans with someone in this room by making up an excuse',
    'Never have I ever screenshotted a convo with someone in this room to share with others',
    'Never have I ever judged someone in this room for their music taste',
    'Never have I ever wanted to tell someone in this room a secret but chickened out',
    'Never have I ever had a competition with someone in this room without them knowing',
    'Never have I ever been annoyed by someone in this room\'s laugh or habit',
    'Never have I ever had a secret handshake with someone in this room',
    'Never have I ever borrowed clothes from someone in this room without asking',
    'Never have I ever faked enjoying an activity just to spend time with someone in this room',
    'Never have I ever texted someone else while hanging out with someone in this room',
    'Never have I ever intentionally made someone in this room jealous',

    // Gen Z Culture
    'Never have I ever said "no cap" in a serious conversation',
    'Never have I ever used the word "cheugy" unironically',
    'Never have I ever done a TikTok dance in public',
    'Never have I ever pretended to know about a meme I didn\'t understand',
    'Never have I ever said "bet" to everything for an entire day',
    'Never have I ever texted someone sitting in the same room as me',
    'Never have I ever posted on BeReal more than 2 hours late',
    'Never have I ever sent someone a Snapchat that was meant for my story',
    'Never have I ever called something "mid" just because everyone else did',
    'Never have I ever canceled plans because of "bad vibes"',
    'Never have I ever used an Instagram filter to hide a bad skin day',
    'Never have I ever bought something just because it was trending on TikTok',
    'Never have I ever used the excuse "no printer, just fax" in a conversation',
    'Never have I ever had a "soft launch" of a relationship on social media',
    'Never have I ever claimed to be the "main character"',
    'Never have I ever called something "fire" that was actually terrible',
    'Never have I ever used the phrase "living rent-free in my head"',
    'Never have I ever participated in a TikTok challenge',
    'Never have I ever used the word "slay" in everyday conversation',
    'Never have I ever ghost-watched someone\'s Instagram stories for months',
    
    // Random Fun
    'Never have I ever been caught singing in the shower',
    'Never have I ever tripped and fallen in public and pretended I meant to do it',
    'Never have I ever pretended to be busy to avoid helping someone move',
    'Never have I ever had a wardrobe malfunction in public',
    'Never have I ever laughed so hard I peed a little',
    'Never have I ever been jealous of a sibling',
    'Never have I ever pretended to know a celebrity',
    'Never have I ever farted in public and blamed someone else',
    'Never have I ever gotten lost following GPS directions',
    'Never have I ever accidentally called someone "mom" or "dad" who wasn\'t my parent',
    'Never have I ever sent a screenshot of a conversation to the person I was talking about by mistake',
    'Never have I ever walked into a pole or door while looking at my phone',
    'Never have I ever pretended to be on the phone to avoid someone',
    'Never have I ever ugly-cried during a movie',
    'Never have I ever accidentally liked a photo while stalking someone online',
    'Never have I ever gotten food delivered because I was too lazy to cook',
    'Never have I ever talked to a pet like they were a person',
    'Never have I ever practiced a conversation in the mirror',
    'Never have I ever taken a selfie in a public bathroom',
    'Never have I ever had a crush on a fictional character',
    
    // Dynamic Prompts (Player vs. Player)
    'Between [player] and [random player], never have I ever thought one was more dramatic',
    'Between [player] and [random player], never have I ever been more annoyed by one of them',
    'Between [player] and [random player], never have I ever trusted one more with a secret',
    'Between [player] and [random player], never have I ever thought one was a better dresser',
    'Between [player] and [random player], never have I ever found one funnier than the other',
    'Between [player] and [random player], never have I ever been more intimidated by one',
    'Between [player] and [random player], never have I ever been more impressed by one\'s talents',
    'Between [player] and [random player], never have I ever thought one was more likely to be famous',
    'Between [player] and [random player], never have I ever found one easier to talk to',
    'Between [player] and [random player], never have I ever wanted to spend more time with one',
    'Between [player] and [random player], never have I ever felt more comfortable around one',
    'Between [player] and [random player], never have I ever thought one was more likely to succeed',
    'Between [player] and [random player], never have I ever found one\'s stories more interesting',
    'Between [player] and [random player], never have I ever been more excited to hang out with one',
    'Between [player] and [random player], never have I ever been more influenced by one',
    'Between [player] and [random player], never have I ever trusted one\'s advice more',
    'Between [player] and [random player], never have I ever found one more mysterious',
    'Between [player] and [random player], never have I ever thought one was more extroverted',
    'Between [player] and [random player], never have I ever thought one was more adventurous',
    'Between [player] and [random player], never have I ever thought one was more reliable',
    
    // More Social Media
    'Never have I ever unfollowed and refollowed someone just to get their attention',
    'Never have I ever used the "Close Friends" story to be petty',
    'Never have I ever posted something cryptic hoping a specific person would see it',
    'Never have I ever stalked someone\'s ex on social media',
    'Never have I ever deleted a post because it didn\'t get enough likes',
    'Never have I ever posted something just to make someone jealous',
    'Never have I ever lurked on a dating app without making a profile',
    'Never have I ever pretended I didn\'t see someone\'s message when I did',
    'Never have I ever posted a thirst trap right after a breakup',
    'Never have I ever taken more than 20 selfies to get the perfect one',
    'Never have I ever checked who viewed my Instagram story multiple times a day',
    'Never have I ever accidentally video called someone in the middle of the night',
    'Never have I ever stalked my crush\'s Spotify activity',
    'Never have I ever googled myself',
    'Never have I ever sent someone a passive-aggressive reaction emoji',
    'Never have I ever found someone\'s secret social media account',
    'Never have I ever pretended to be interested in someone\'s photos just to keep scrolling through their profile',
    'Never have I ever "hearted" a message just to end a conversation',
    'Never have I ever forgotten I was on a video call and did something embarrassing',
    'Never have I ever gone through all the tagged photos of someone I just met',
    
    // More Gen Z Culture
    'Never have I ever used an emoji ironically',
    'Never have I ever replied with just "💀"',
    'Never have I ever said "it\'s giving..." to describe something',
    'Never have I ever faked a British accent after watching too much UK TV',
    'Never have I ever canceled someone for something they posted years ago',
    'Never have I ever used "rizz" in a sentence',
    'Never have I ever called something "based" in a conversation',
    'Never have I ever sent a photo of myself crying to someone',
    'Never have I ever pretended to understand crypto when I had no idea what I was talking about',
    'Never have I ever made a finsta just for my close friends',
    'Never have I ever used "gaslighting" in the wrong context',
    'Never have I ever said "I feel seen" when someone described something relatable',
    'Never have I ever used the phrase "touch grass" to someone',
    'Never have I ever called something "core" (cottagecore, normcore, etc.)',
    'Never have I ever taken a "photo dump" just because I looked good in one picture',
    'Never have I ever caught the "ick" from something insignificant',
    'Never have I ever used "delulu" unironically',
    'Never have I ever had a "situationship"',
    'Never have I ever posted sad song lyrics hoping someone specific would see',
    'Never have I ever used "chronically online" as an insult',
  ],
),
  GameMode(
    id: 'most_likely_to',
    name: 'Most Likely To',
    description: 'Find out what your friends really think about who would most likely do what!',
    icon: '👀',
    isPremium: true,
    category: 'Classics',
    samplePrompts: [
      'Most likely to become a meme',
      'Most likely to win an eating contest',
      'Most likely to get arrested (for something minor)',
      'Most likely to become a TikTok star',
      'Most likely to invent something world-changing',
      'Most likely to survive a zombie apocalypse',
      'Most likely to write a bestselling novel',
      'Most likely to date a celebrity',
      'Most likely to go viral for something embarrassing',
      'Most likely to live off the grid',
      'Most likely to become a millionaire',
      'Most likely to move abroad',
      'Most likely to become famous',
      'Most likely to get married first',
      'Most likely to win the lottery',
      'Most likely to become a doctor',
      'Most likely to become a lawyer',
      'Most likely to become a teacher',
      'Most likely to become a chef',
      'Most likely to become a musician',
      'Most likely to become a writer',
      'Most likely to become an artist',
      'Most likely to become a scientist',
      'Most likely to become a politician',
      'Most likely to become a model',
      'Most likely to become an actor',
      'Most likely to become a dancer',
      'Most likely to become a singer',
      'Most likely to become a comedian',
      'Most likely to become a photographer',
      'Most likely to become a designer',
      'Most likely to become a programmer',
      'Most likely to become a gamer',
      'Most likely to become a chef',
      'Most likely to become a musician',
      'Most likely to become a writer',
      'Most likely to become an artist',
      'Most likely to become a scientist',
      'Most likely to become a politician',
      'Most likely to become a model',
      'Most likely to become an actor',
      'Most likely to become a dancer',
      'Most likely to become a singer',
      'Most likely to become a comedian',
      'Most likely to become a photographer',
      'Most likely to become a designer',
      'Most likely to become a programmer',
      'Most likely to become a gamer',
    ],
  ),
  GameMode(
    id: 'couples_night',
    name: 'Couples Night',
    description: 'Perfect for date night or couples party with romantic and fun challenges.',
    icon: '❤️',
    isPremium: true,
    category: 'Special Occasions',
    samplePrompts: [
      'Give your partner a gentle kiss',
      'Hold your partner\'s hand and look into their eyes',
      'Give your partner a warm hug',
      'Tell your partner what you love about them',
      'Give your partner a gentle massage',
      'Hold your partner close and slow dance',
      'Give your partner a sweet kiss on the cheek',
      'Tell your partner a romantic story',
      'Give your partner a gentle back rub',
      'Hold your partner\'s hand and walk together',
      'Give your partner a gentle kiss',
      'Hold your partner\'s hand and look into their eyes',
      'Give your partner a warm hug',
      'Tell your partner what you love about them',
      'Give your partner a gentle massage',
      'Hold your partner close and slow dance',
      'Give your partner a sweet kiss on the cheek',
      'Tell your partner a romantic story',
      'Give your partner a gentle back rub',
      'Hold your partner\'s hand and walk together',
      'Give your partner a gentle kiss',
      'Hold your partner\'s hand and look into their eyes',
      'Give your partner a warm hug',
      'Tell your partner what you love about them',
      'Give your partner a gentle massage',
      'Hold your partner close and slow dance',
      'Give your partner a sweet kiss on the cheek',
      'Tell your partner a romantic story',
      'Give your partner a gentle back rub',
      'Hold your partner\'s hand and walk together',
      'Give your partner a gentle kiss',
      'Hold your partner\'s hand and look into their eyes',
      'Give your partner a warm hug',
      'Tell your partner what you love about them',
      'Give your partner a gentle massage',
      'Hold your partner close and slow dance',
      'Give your partner a sweet kiss on the cheek',
      'Tell your partner a romantic story',
      'Give your partner a gentle back rub',
      'Hold your partner\'s hand and walk together',
      'Give your partner a gentle kiss',
      'Hold your partner\'s hand and look into their eyes',
      'Give your partner a warm hug',
      'Tell your partner what you love about them',
      'Give your partner a gentle massage',
      'Hold your partner close and slow dance',
      'Give your partner a sweet kiss on the cheek',
      'Tell your partner a romantic story',
      'Give your partner a gentle back rub',
      'Hold your partner\'s hand and walk together',
    ],
  ),
  GameMode(
    id: 'girls_night',
    name: 'Girls Night',
    description: 'Ultimate girls night out edition with female-focused fun and challenges.',
    icon: '👯‍♀️',
    isPremium: true,
    category: 'Special Occasions',
    samplePrompts: [
      'Share your worst first date story',
      'What\'s the most embarrassing thing you\'ve ever done in front of a crush?',
      'What\'s the weirdest text you\'ve ever received?',
      'What\'s your biggest dating dealbreaker?',
      'What\'s the most romantic thing a guy has ever done for you?',
      'Drink if you\'ve ever borrowed clothes without asking',
      'Take a sip if you\'ve cried watching a romance movie',
      'Everyone wearing makeup drinks',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  GameMode(
    id: 'boys_night',
    name: 'Boys Night',
    description: 'Bros night out challenges designed for the guys to have a great time.',
    icon: '🤜🤛',
    isPremium: true,
    category: 'Special Occasions',
    samplePrompts: [
      'What\'s the most embarrassing thing you\'ve ever done to try and impress a girl?',
      'What\'s your biggest fear in a relationship?',
      'What\'s the weirdest pick-up line you\'ve ever used?',
      'What\'s your biggest dating pet peeve?',
      'What\'s the most romantic thing you\'ve ever done?',
      'Drink if you\'ve ever tried to impress someone at the gym',
      'Take a shot if you\'ve lost in FIFA today',
      'Everyone with a beard drinks twice',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  GameMode(
    id: 'truth_or_drink',
    name: 'Truth or Drink',
    description: 'Answer truthfully to personal questions or take a drink to avoid answering!',
    icon: '🤫',
    isPremium: true,
    category: 'Classics',
    samplePrompts: [
      'What\'s your biggest regret or take a drink',
      'Reveal your last DM or drink twice',
      'Share your most embarrassing moment or finish your drink',
      'Current player, if you\'ve ever cheated on your partner, take 2 drinks',
      'Everyone who\'s been in a long-distance relationship drinks',
    ],
  ),
  GameMode(
    id: 'party_challenges',
    name: 'Party Challenges',
    description: 'Exciting physical and mental challenges to spice up the night and get everyone involved.',
    icon: '🎉',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Try to fit your whole fist in your mouth',
      'Sing a song in a different language (or make one up)',
      'Eat a spoonful of something spicy',
      'Give someone a piggyback ride around the room',
      'Do a handstand against the wall',
      'Try to lick your elbow',
      'Say the alphabet backward',
      'Hold an ice cube in your hand until it melts',
      'Stand on one leg for 30 seconds',
      'Do a cartwheel (or attempt one)',
      'Challenge someone to a dance-off or drink',
      'Do your best celebrity impression or take two drinks',
      'Make everyone laugh or finish your drink',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  GameMode(
    id: 'wildcards',
    name: 'Wildcards',
    description: 'Expect the unexpected with these random and surprising game-changing challenges.',
    icon: '🃏',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Everyone takes a shot',
      'Pick someone to skip their next turn',
      'Reverse the order of play',
      'The person to your left drinks',
      'The person to your right drinks',
      'Waterfall: Everyone drinks until the person who picked the card stops',
      'Thumb Master: Last person to put their thumb on the table drinks',
      'Make a Rule: Invent a new rule that everyone must follow for the rest of the game',
      'Categories: Choose a category and go around the circle naming things in that category. First person to repeat or hesitate drinks',
      'Rhyme Time: Say a word. The next person has to say a word that rhymes. Continue until someone can\'t think of a rhyme',
      'Switch drinks with the person to your right',
      'Everyone trades seats and drinks',
      'Create a new rule for the game',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  
  // Flirty Fun mode in Classics category
  GameMode(
    id: 'flirty_fun',
    name: 'Flirty Fun',
    description: 'Playful questions and light challenges to create chemistry and break the ice.',
    icon: '💋',
    isPremium: true,
    category: 'Classics',
    samplePrompts: [
      'Compliment the person to your left on something other than their looks',
      'Describe your celebrity crush',
      'Share your biggest turn-off (in a dating context)',
      'Rate the attractiveness of a fictional character',
      'Tell a cheesy pick-up line',
      'Impersonate someone\'s dating profile picture',
      'Do your best seductive pose',
      'Whisper a compliment to the person on your right',
      'Have a staring contest with someone you find attractive',
      'Play "kiss, marry, kill" with fictional characters',
      'Current player, give a compliment to another player or take a drink',
      'Everyone votes on who has the best smile. Current player counts to 3!',
      'Current player, share your best pickup line or take two drinks',
      'Current player, if you\'ve ever had a crush on someone in this room, take a drink',
      'Truth: Current player, who in this room would you go on a date with?',
      'Current player, make eye contact with another player for 10 seconds or drink',
      'Everyone who\'s been on a date this month drinks',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  
  // Heat It Up mode in Challenges category
  GameMode(
    id: 'heat_it_up',
    name: 'Heat It Up',
    description: 'More daring challenges that push comfort zones and increase intimacy.',
    icon: '🔥',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Never have I ever fantasized about someone in this room',
      'Most likely to have a secret admirer',
      'What\'s the most attractive quality in a person?',
      'Act out a suggestive word or phrase (keep it PG-13)',
      'Two players exchange increasingly flirty compliments',
      'Everyone anonymously writes down their favorite body part on themselves. Read them aloud and guess who wrote what',
      'Set up a "kissing booth" (a designated chair). Anyone can choose to go in for a kiss on the cheek from anyone else (with clear consent)',
      'Truth or Dare: Truths and dares with a flirty/suggestive theme, but nothing explicit',
      'Would you rather go on a date with [person 1] or [person 2]?',
      'Anonymously rate someone\'s outfit on a scale of 1-10',
      'Current player, whisper something in another player\'s ear that would make them blush',
      'Current player, take a body shot off of another player or take three drinks',
      'Everyone votes on who\'s the most seductive. Current player counts to 3!',
      'Current player, demonstrate your best dance move or finish your drink',
      'Current player, share a secret fantasy or take two drinks',
      'Current player and another player must hold hands until the next round',
      'Everyone who\'s kissed someone in the last week drinks',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  
  // No Limits mode in Challenges category
  GameMode(
    id: 'no_limits',
    name: 'No Limits',
    description: 'The most provocative and intimate category for those looking to push boundaries.',
    icon: '🌶️',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Never have I ever had a threesome',
      'What\'s your wildest sexual fantasy?',
      'Most likely to join OnlyFans',
      'Write down an anonymous sexual confession (within legal and ethical boundaries). Read them aloud and try to guess who wrote what',
      'Start a story with a sexually suggestive sentence (within legal and ethical boundaries). Each person adds a sentence',
      'Act out a consensual sexual scenario (within legal and ethical boundaries)',
      'Truth or Dare: Truths and dares with an explicit sexual theme (within legal and ethical boundaries, and with enthusiastic consent)',
      'Would you rather [explicit sexual scenario 1] or [explicit sexual scenario 2]?',
      'Like a fantasy football draft, but with sexual fantasies (within legal and ethical boundaries)',
      'Fill in the blanks to create a funny and erotic story (within legal and ethical boundaries)',
      'Write down your wildest fantasy anonymously. Everyone tries to guess who wrote what',
      'Strip down to your underwear and do a sexy dance for everyone',
      'Give someone a sensual massage for 30 seconds',
      'Let someone kiss your neck for 30 seconds',
      'Give someone a lap dance for 30 seconds',
      'Strip tease for the group',
      'Let someone caress your body for 30 seconds',
      'Give someone a sensual foot massage',
      'Let someone kiss your inner thighs',
      'Give someone a sensual back massage',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  GameMode(
    id: 'wild',
    name: 'Wild',
    description: 'Adventurous challenges that push boundaries while keeping it fun and consensual.',
    icon: '🐯',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Strip down to your underwear and dance',
      'Give someone a lap dance',
      'Let someone kiss your neck',
      'Give someone a sensual massage',
      'Let someone caress your body',
      'Strip tease for the group',
      'Give someone a sensual foot massage',
      'Let someone kiss your inner thighs',
      'Give someone a sensual back massage',
      'Let someone caress your sensitive spots',
      'Strip down to your underwear and dance',
      'Give someone a lap dance',
      'Let someone kiss your neck',
      'Give someone a sensual massage',
      'Let someone caress your body',
      'Strip tease for the group',
      'Give someone a sensual foot massage',
      'Let someone kiss your inner thighs',
      'Give someone a sensual back massage',
      'Let someone caress your sensitive spots',
      'Strip down to your underwear and dance',
      'Give someone a lap dance',
      'Let someone kiss your neck',
      'Give someone a sensual massage',
      'Let someone caress your body',
      'Strip tease for the group',
      'Give someone a sensual foot massage',
      'Let someone kiss your inner thighs',
      'Give someone a sensual back massage',
      'Let someone caress your sensitive spots',
      'Strip down to your underwear and dance',
      'Give someone a lap dance',
      'Let someone kiss your neck',
      'Give someone a sensual massage',
      'Let someone caress your body',
      'Strip tease for the group',
      'Give someone a sensual foot massage',
      'Let someone kiss your inner thighs',
      'Give someone a sensual back massage',
      'Let someone caress your sensitive spots',
    ],
  ),
]; 