class GameMode {
  final String id;
  final String name;
  final String description;
  final String icon;
  final bool isPremium;
  final List<String> samplePrompts;
  final String category;
  bool isSelected;

  GameMode({
    required this.id,
    required this.name,
    required this.description,
    required this.icon,
    required this.isPremium,
    required this.samplePrompts,
    required this.category,
    this.isSelected = false,
  });
}

final List<GameMode> gameModes = [
  // Free Modes
  GameMode(
    id: 'getting_started',
    name: 'Getting Started',
    description: 'Perfect for warming up the party with simple drinking rules and challenges.',
    icon: '🎮',
    isPremium: false,
    category: 'Warm-Up (Free)',
    samplePrompts: [
      'Sip or Spill: If you\'ve ever slid into someone\'s DMs and regretted it',
      'Sip or Spill: If you\'ve ever pretended to know a TikTok dance you didn\'t',
      'Sip or Spill: If you\'ve ever worn the same clothes for multiple days in a row',
      'Sip or Spill: If you\'ve ever faked being sick to avoid a social obligation',
      'Sip or Spill: If you\'ve ever stalked an ex\'s new partner online',
      'Sip or Spill: If you\'ve ever lied about your age to get into a bar/club',
      'Sip or Spill: If you\'ve ever used a dating app just for validation',
      'Sip or Spill: If you\'ve ever taken a screenshot of someone\'s social media post without their knowledge',
      'Sip or Spill: If you\'ve ever accidentally liked an old Instagram post',
      'Sip or Spill: If you\'ve ever pretended to be interested in someone\'s story',
      'Last person to touch their nose drinks',
      'Current player, choose someone to take a drink with you',
      'Everyone wearing jeans drinks',
      'Current player and another player must play rock, paper, scissors. Loser drinks!',
      'Last person to stand up drinks',
      'Current player, give out drinks equal to your age',
      'Everyone who\'s been on a date this month drinks',
      'Everyone with a pet drinks',
      'Current player and another player must do a dance-off. Loser drinks!',
      'Last person to check their phone drinks',
      'Everyone who\'s traveled abroad drinks',
      'Current player, give 3 drinks to someone who makes you laugh',
      'Everyone wearing black drinks',
      'Last person to say "cheers" drinks',
      'Current player, choose someone to do a shot with',
      'Everyone who\'s been to a concert drinks',
      'Current player and another player must tell a joke. Worst joke drinks!',
      'Last person to touch their drink drinks',
      'Everyone who\'s been to college drinks',
      'Current player, give drinks to people who make you smile',
      'Everyone wearing sneakers drinks',
      'Last person to say "I love you" drinks',
      'Current player, choose someone to do a dance with',
      'Everyone who\'s been in a car accident drinks',
      'Current player and another player must sing a song. Worst singer drinks!',
      'Last person to laugh drinks',
      'Everyone who\'s been to a wedding drinks',
      'Current player, give drinks to people who make you happy',
      'Everyone wearing a watch drinks',
      'Last person to say "thank you" drinks',
      'Everyone who\'s been to a funeral drinks',
      'Current player and another player must tell a story. Worst story drinks!',
      'Last person to touch their face drinks',
      'Everyone who\'s been to a party drinks',
      'Everyone wearing a ring drinks',
    ],
  ),
  GameMode(
    id: 'getting_tipsy',
    name: 'Getting Tipsy',
    description: 'Step it up a notch with more challenging and entertaining drinking tasks.',
    icon: '🍻',
    isPremium: false,
    category: 'Warm-Up (Free)',
    samplePrompts: [
      'Current player, if you\'ve ever been caught in a lie, give out 3 drinks',
      'Everyone who\'s been late today drinks',
      'Current player gives out drinks equal to their siblings',
      'Current player and another player must play rock, paper, scissors. Loser drinks!',
      'Current player, if you got ghosted after a date, give out 2 drinks',
      'Current player, if you\'ve ever cheated on a test, take 2 drinks',
      'Everyone who\'s been to a club drinks',
      'Current player and another player must do a dance-off. Loser drinks!',
      'Current player, if you\'ve ever been fired, take 3 drinks',
      'Everyone who\'s been to a bar drinks',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must tell a joke. Worst joke drinks!',
      'Current player, if you\'ve ever been in a fight, take 2 drinks',
      'Everyone who\'s been to a concert drinks',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must sing a song. Worst singer drinks!',
      'Current player, if you\'ve ever been arrested, take 3 drinks',
      'Everyone who\'s been to a wedding drinks',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story. Worst story drinks!',
      'Current player, if you\'ve ever been in a car accident, take 2 drinks',
      'Everyone who\'s been to a funeral drinks',
      'Current player and another player must do a shot together',
      'Current player, if you\'ve ever been in a long-distance relationship, take 2 drinks',
      'Everyone who\'s been to college drinks',
      'Current player and another player must do a dance together',
      'Current player, if you\'ve ever had a one-night stand, take a drink',
      'Everyone who\'s been to a party drinks',
      'Current player and another player must tell a secret',
      'Current player, if you\'ve ever been in a threesome, take a drink',
    ],
  ),

  // Premium Modes
  GameMode(
    id: 'never_have_i_ever',
    name: 'Never Have I Ever',
    description: 'Classic drinking game with a twist! Reveal secrets and drink to what you\'ve done.',
    icon: '🤔',
    isPremium: true,
    category: 'Classics',
    samplePrompts: [
      'Never have I ever used someone else\'s streaming account',
      'Never have I ever regifted a present',
      'Never have I ever pretended to be someone else online',
      'Never have I ever sneaked food into a movie theater',
      'Never have I ever gone a week without showering',
      'Never have I ever lied about my age on a dating app',
      'Never have I ever drunk dialed someone',
      'Never have I ever had a wardrobe malfunction',
      'Never have I ever slept through an important event',
      'Never have I ever broken something and blamed someone else',
      'Never have I ever sent a text to the wrong person',
      'Never have I ever gone skinny dipping',
      'Never have I ever faked being sick to skip work',
      'Never have I ever cheated on a test',
      'Never have I ever been arrested',
      'Never have I ever been in a fight',
      'Never have I ever been fired',
      'Never have I ever been to a club',
      'Never have I ever been to a bar',
      'Never have I ever been to a concert',
      'Never have I ever been to a wedding',
      'Never have I ever been to a funeral',
      'Never have I ever been to college',
      'Never have I ever been to a party',
      'Never have I ever been late to work',
      'Never have I ever ghosted someone',
      'Never have I ever had a crush on someone in this room',
      'Never have I ever been in a long-distance relationship',
      'Never have I ever had a one-night stand',
      'Never have I ever been in a threesome',
      'Never have I ever been in a car accident',
      'Never have I ever been in a fight',
      'Never have I ever been arrested',
      'Never have I ever been to a wedding',
      'Never have I ever been to a funeral',
      'Never have I ever been to college',
      'Never have I ever been to a party',
      'Never have I ever been to a bar',
      'Never have I ever been to a concert',
      'Never have I ever been to a wedding',
      'Never have I ever been to a funeral',
      'Never have I ever been to college',
      'Never have I ever been to a party',
    ],
  ),
  GameMode(
    id: 'most_likely_to',
    name: 'Most Likely To',
    description: 'Find out what your friends really think about who would most likely do what!',
    icon: '👀',
    isPremium: true,
    category: 'Classics',
    samplePrompts: [
      'Most likely to become a meme',
      'Most likely to win an eating contest',
      'Most likely to get arrested (for something minor)',
      'Most likely to become a TikTok star',
      'Most likely to invent something world-changing',
      'Most likely to survive a zombie apocalypse',
      'Most likely to write a bestselling novel',
      'Most likely to date a celebrity',
      'Most likely to go viral for something embarrassing',
      'Most likely to live off the grid',
      'Most likely to become a millionaire',
      'Most likely to move abroad',
      'Most likely to become famous',
      'Most likely to get married first',
      'Most likely to win the lottery',
      'Most likely to become a doctor',
      'Most likely to become a lawyer',
      'Most likely to become a teacher',
      'Most likely to become a chef',
      'Most likely to become a musician',
      'Most likely to become a writer',
      'Most likely to become an artist',
      'Most likely to become a scientist',
      'Most likely to become a politician',
      'Most likely to become a model',
      'Most likely to become an actor',
      'Most likely to become a dancer',
      'Most likely to become a singer',
      'Most likely to become a comedian',
      'Most likely to become a photographer',
      'Most likely to become a designer',
      'Most likely to become a programmer',
      'Most likely to become a gamer',
      'Most likely to become a chef',
      'Most likely to become a musician',
      'Most likely to become a writer',
      'Most likely to become an artist',
      'Most likely to become a scientist',
      'Most likely to become a politician',
      'Most likely to become a model',
      'Most likely to become an actor',
      'Most likely to become a dancer',
      'Most likely to become a singer',
      'Most likely to become a comedian',
      'Most likely to become a photographer',
      'Most likely to become a designer',
      'Most likely to become a programmer',
      'Most likely to become a gamer',
    ],
  ),
  GameMode(
    id: 'couples_night',
    name: 'Couples Night',
    description: 'Perfect for date night or couples party. Perform the action or both drink!',
    icon: '❤️',
    isPremium: true,
    category: 'Special Occasions',
    samplePrompts: [
      'Give your partner a gentle kiss. Or both drink.',
      'Hold your partner\\\'s hand and look into their eyes for 10 seconds. Or both drink.',
      'Give your partner a warm hug lasting at least 5 seconds. Or both drink.',
      'Tell your partner one specific thing you love about them. Or both drink.',
      'Give your partner a gentle shoulder massage for 30 seconds. Or both drink.',
      'Hold your partner close and slow dance (even without music) for 15 seconds. Or both drink.',
      'Give your partner a sweet kiss on the cheek. Or both drink.',
      'Tell your partner a short, romantic story (can be made up). Or both drink.',
      'Whisper a compliment into your partner\\\'s ear. Or both drink.',
      'Serenade your partner with a line from a love song. Or both drink.',
      'Share a happy memory you have with your partner. Or both drink.',
      'Describe your partner in three positive words. Or both drink.',
      'Give your partner a foot rub for 1 minute (if comfortable). Or both drink.',
      'Feed your partner a snack or a sip of their drink. Or both drink.',
      'Recreate your first kiss (briefly!). Or both drink.',
    ],
  ),
  GameMode(
    id: 'girls_night',
    name: 'Girls Night',
    description: 'Ultimate girls night out edition with fun questions and challenges.',
    icon: '👯‍♀️',
    isPremium: true,
    category: 'Special Occasions',
    samplePrompts: [
      'Share your worst first date story.',
      'What\\\'s the most embarrassing thing you\\\'ve ever done in front of a crush?',
      'What\\\'s the weirdest text you\\\'ve ever received?',
      'What\\\'s your biggest dating dealbreaker?',
      'What\\\'s the most romantic thing someone has ever done for you?',
      'Drink if you\\\'ve ever borrowed clothes without asking.',
      'Take a sip if you\\\'ve cried watching a romance movie.',
      'Everyone wearing makeup drinks.',
      'Drink if you have ever sent a risky text and immediately regretted it.',
      'Take a sip if you currently have a secret crush.',
      'Everyone who has posted a selfie today drinks.',
      'What celebrity would you want to be your best friend?',
      'Sip or Spill: Have you ever lied to get out of a bad date?',
      'If you could swap lives with any woman here for a day, who and why?',
      'What\\\'s your go-to "getting ready" song?',
      'Drink if you\\\'ve ever practiced a fake argument in the mirror.',
      'Take a sip if you know the horoscope sign of everyone in this room.',
      'Everyone who is currently single drinks.',
      'Share your favorite gossip story (anonymously, if needed!).',
      'What trend do you secretly miss?',
      'Drink if you\\\'ve ever used a dating app just for the ego boost.',
      'Who here gives the best advice? That person gives out 3 drinks.',
      'Take a sip for every piercing you have (ears count as 1 total).',
      'Everyone who has ever dyed their hair an unnatural color drinks.',
      'What reality TV show would you thrive on?',
    ],
  ),
  GameMode(
    id: 'boys_night',
    name: 'Boys Night',
    description: 'Bros night out challenges designed for the guys to have a great time.',
    icon: '🤜🤛',
    isPremium: true,
    category: 'Special Occasions',
    samplePrompts: [
      'What\\\'s the most embarrassing thing you\\\'ve ever done to try and impress someone?',
      'What\\\'s your biggest fear in a relationship?',
      'What\\\'s the weirdest pick-up line you\\\'ve ever used?',
      'What\\\'s your biggest dating pet peeve?',
      'What\\\'s the most "alpha" thing you\\\'ve ever done (or witnessed)?',
      'Drink if you\\\'ve ever tried to impress someone at the gym.',
      'Take a shot if you\\\'ve lost a bet recently.',
      'Everyone with a beard drinks twice.',
      'Drink if you have ever cried during a sports movie.',
      'Take a sip if you secretly enjoy romantic comedies.',
      'Everyone who has skipped leg day this week drinks.',
      'What fictional character represents your ideal self?',
      'Sip or Spill: Have you ever been caught checking someone out?',
      'If you could have a beer with any historical figure, who?',
      'What\\\'s your ultimate "dad joke"? Tell it or drink.',
      'Drink if you\\\'ve ever used Axe body spray unironically.',
      'Take a sip if you can name more than 5 types of beer.',
      'Everyone who thinks they could win a fight against a kangaroo drinks.',
      'Share your most legendary drinking story.',
      'What superpower would be most useful for picking up girls/guys?',
    ],
  ),
  GameMode(
    id: 'truth_or_drink',
    name: 'Truth or Drink',
    description: 'Answer truthfully to personal questions or take a drink to avoid answering!',
    icon: '🤫',
    isPremium: true,
    category: 'Classics',
    samplePrompts: [
      'What\\\'s your biggest regret? Answer or drink.',
      'Reveal your last DM. Answer or drink twice.',
      'Share your most embarrassing moment. Answer or finish your drink.',
      'Have you ever cheated on a partner? Answer or take 2 drinks.',
      'Who was your first celebrity crush? Answer or drink.',
      'What\\\'s the biggest lie you\\\'ve ever told? Answer or drink.',
      'Have you ever stolen anything? Answer or drink twice.',
      'What password do you use most often (don\\\'t say it!)? Hint or finish your drink.',
      'What\\\'s your guilty pleasure song? Sing a line or drink.',
      'Have you ever peed in a pool? Answer or drink.',
      'What\\\'s the weirdest thing you find attractive? Answer or drink twice.',
      'Do you believe in ghosts? Answer or drink.',
      'Who in this room would you trust with a secret? Answer or drink.',
      'Have you ever faked being sick to avoid something? Answer or finish your drink.',
      'What\\\'s the longest you\\\'ve gone without showering? Answer or take 2 drinks.',
    ],
  ),
  GameMode(
    id: 'party_challenges',
    name: 'Party Challenges',
    description: 'Exciting physical and mental challenges. Fail or refuse, and you drink!',
    icon: '🎉',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Try to fit your whole fist in your mouth. Or drink.',
      'Sing a song in a different language (or make one up). Or drink.',
      'Eat a spoonful of something spicy (chosen by group). Or drink.',
      'Give someone a piggyback ride around the room. Or drink.',
      'Do a handstand against the wall for 5 seconds. Or drink.',
      'Try to lick your elbow. Or drink.',
      'Say the alphabet backward in 15 seconds. Or drink.',
      'Hold an ice cube in your hand until it melts. Or drink.',
      'Stand on one leg for 30 seconds without wobbling. Or drink.',
      'Do a cartwheel (or attempt one safely). Or drink.',
      'Challenge someone to a dance-off. Loser drinks.',
      'Do your best celebrity impression. If group doesn\\\'t guess in 3 tries, drink.',
      'Make everyone laugh with a joke or story. If you fail, finish your drink.',
      'Balance a cup/bottle on your head for 1 minute. Or drink.',
      'Do 10 push-ups. Or drink.',
      'Recite a tongue twister 3 times fast without errors. Or drink.',
      'Let someone draw on your face with a washable marker. Or drink.',
      'Arm wrestle the person to your left. Loser drinks.',
      'Try to juggle 3 objects for 10 seconds. Or drink.',
      'Hold a plank for 30 seconds. Or drink.',
    ],
  ),
  GameMode(
    id: 'wildcards',
    name: 'Wildcards',
    description: 'Expect the unexpected with these random game-changing challenges.',
    icon: '🃏',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Everyone takes a shot!',
      'Pick someone to skip their next turn.',
      'Reverse the order of play.',
      'The person to your left drinks.',
      'The person to your right drinks.',
      'Waterfall! Everyone starts drinking. You can only stop when the person before you stops. Player who drew card starts.',
      'Thumb Master! Be the last person to put their thumb on the table when the card drawer secretly does. Last thumb down drinks.',
      'Make a Rule! Invent a new rule (e.g., no first names, must speak in accent). Rule lasts until next Make a Rule card. Break rule = drink.',
      'Categories! Player chooses a category (e.g., car brands, dog breeds). Go around naming items. First to hesitate or repeat drinks.',
      'Rhyme Time! Player says a word. Go around saying a word that rhymes. First to fail drinks.',
      'Switch drinks with the person to your right for one round.',
      'Everyone pass their drink one person to the left.',
      'Story Time! Start a story with one word. Go around adding one word each. First to mess up the story drinks.',
      'Question Master! You can only speak in questions until the next Wildcard. Fail = drink.',
      'Never Have I Ever! Player states a "Never have I ever...". Anyone who HAS done it drinks.',
    ],
  ),
  
  // Flirty Fun mode in Classics category
  GameMode(
    id: 'flirty_fun',
    name: 'Flirty Fun',
    description: 'Playful questions and challenges to create chemistry. Refuse or fail = drink!',
    icon: '💋',
    isPremium: true,
    category: 'Classics',
    samplePrompts: [
      'Compliment the person to your left on something other than their looks. Or drink.',
      'Describe your celebrity crush and why. Or drink.',
      'Share your biggest turn-off (in a dating context). Or drink.',
      'Rate the attractiveness of a fictional character (e.g., Shrek) on scale 1-10. Or drink.',
      'Tell the cheesiest pick-up line you know. Or drink.',
      'Impersonate someone\\\'s dating profile picture pose. Or drink.',
      'Do your best seductive pose. Or drink.',
      'Whisper a (clean) compliment to the person on your right. Or drink.',
      'Have a 15-second staring contest with someone you find attractive. First to break contact or laugh drinks.',
      'Play "kiss, marry, kill" with three people in this room (chosen by group). Or drink.',
      'Who here has the best smile? Point on 3. Person with most votes gives out a drink.',
      'Share your best pickup line attempt story (success or fail). Or drink.',
      'Truth: Have you ever had a crush on someone in this room? Drink if yes, or refuse and drink twice.',
      'Make eye contact with another player for 10 seconds without laughing. Or both drink.',
      'Everyone who\\\'s been on a date this month drinks.',
      'Serenade someone with one line from a cheesy love song. Or drink.',
      'Describe your ideal first date in 3 words. Or drink.',
      'Anonymously write down your most attractive feature. Read aloud and guess who wrote what. Wrong guess = drink.',
      'Who would you most like to be stuck on a desert island with from this group? Or drink.',
      'Give someone a PG-rated nickname for the rest of the game. Or drink.',
    ],
  ),
  
  // Heat It Up mode in Challenges category
  GameMode(
    id: 'heat_it_up',
    name: 'Heat It Up',
    description: 'More daring challenges that push comfort zones. Refuse or fail = drink!',
    icon: '🔥',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Never have I ever fantasized about someone in this room. Drink if you have.',
      'Most likely to have a secret admirer. Chosen person drinks.',
      'What\\\'s the most attractive quality in a person? Answer or drink.',
      'Act out a suggestive word or phrase (keep it PG-13). Or drink.',
      'Two players (chosen by group) exchange increasingly flirty compliments for 30 secs. Or both drink.',
      'Everyone anonymously writes their favorite body part on someone else here. Read aloud and guess who wrote what. Wrong guess = drink.',
      'Truth or Dare: Player chooses. Truths/Dares have a flirty/suggestive theme (PG-13). Refuse/Fail = drink.',
      'Would you rather go on a date with [player X] or [player Y]? Answer or drink.',
      'Anonymously rate the current player\\\'s outfit 1-10. Player reads ratings. Lowest score drinks.',
      'Whisper something in another player\\\'s ear that might make them blush. Or drink.',
      'Take a (clean!) body shot (e.g., lick salt off neck/arm, drink shot, bite lime from hand) off another willing player. Or drink three times.',
      'Everyone votes on who\\\'s the most seductive dancer. Person chosen demonstrates for 15 secs or drinks.',
      'Share a secret fantasy (keep it legal/ethical). Or drink twice.',
      'Current player and another player must hold hands until the next round. Refuse = both drink.',
      'Everyone who\\\'s kissed someone in the last week drinks.',
      'Describe the best kiss you\\\'ve ever had (no names!). Or drink.',
      'Blindfolded, guess who is gently touching your hand. Wrong guess = drink.',
      'Give someone a 20-second shoulder rub. Or drink.',
      'Slow dance with someone for 30 seconds. Or both drink.',
      'Rate the player to your left\\\'s kissing potential 1-10. Or drink.',
    ],
  ),
  
  // No Limits mode in Challenges category
  GameMode(
    id: 'no_limits',
    name: 'No Limits',
    description: 'Provocative category for pushing boundaries consensually. Refuse/Fail = drink! **(18+ WARNING)**',
    icon: '🌶️',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Never have I ever had a threesome. Drink if you have.',
      'What\\\'s your wildest sexual fantasy? Describe or drink twice.',
      'Most likely to join OnlyFans. Chosen person drinks.',
      'Write down an anonymous sexual confession (legal/ethical). Read aloud, guess who wrote it. Wrong guess = drink.',
      'Start a story with a sexually suggestive sentence. Each person adds a sentence. First to fail/refuse drinks.',
      'Act out a consensual sexual scenario (PG-13 version!). Or drink.',
      'Truth or Dare: Explicit sexual themes (CONSENT REQUIRED, legal/ethical). Refuse/Fail = drink.',
      'Would you rather [explicit scenario 1] or [explicit scenario 2]? (Ensure legal/ethical). Answer or drink.',
      'Write your wildest fantasy anonymously. Guess who wrote what. Wrong guess = drink.',
      'Strip down to your underwear and dance for 30 seconds. Or drink three times.',
      'Give someone a sensual massage (shoulders/back) for 30 seconds. Or drink.',
      'Let someone kiss your neck for 15 seconds (CONSENT REQUIRED). Or drink.',
      'Give someone a lap dance for 30 seconds (CONSENT REQUIRED). Or drink.',
      'Strip tease one item of clothing chosen by group. Or drink twice.',
      'Let someone caress your arm/leg for 30 seconds (CONSENT REQUIRED). Or drink.',
      'Give someone a sensual foot massage for 1 minute (if comfortable). Or drink.',
      'Let someone kiss your inner thighs (over clothes, CONSENT REQUIRED). Or drink twice.',
      'Player describes their ideal hookup scenario. Or drink.',
      'Rate your own sexual performance 1-10. Or drink.',
      'Blindfolded, guess who is whispering something suggestive in your ear. Wrong guess = drink.',
    ],
  ),
  GameMode(
    id: 'wild',
    name: 'Wild',
    description: 'Adventurous physical challenges pushing boundaries consensually. Refuse = drink! **(18+ WARNING)**',
    icon: '🐯',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Strip down to your underwear and dance for 1 minute. Or drink three times.',
      'Give someone a lap dance for 1 minute (CONSENT REQUIRED). Or drink twice.',
      'Let someone kiss your neck passionately for 30 seconds (CONSENT REQUIRED). Or drink.',
      'Give someone a sensual massage (back/shoulders) for 1 minute (CONSENT REQUIRED). Or drink.',
      'Let someone caress your body (arms/legs/back) for 1 minute (CONSENT REQUIRED). Or drink.',
      'Perform a strip tease removing two items of clothing (chosen by group). Or drink three times.',
      'Give someone a sensual foot massage for 2 minutes (if comfortable). Or drink.',
      'Let someone kiss your inner thighs (over clothes, CONSENT REQUIRED) for 30 seconds. Or drink twice.',
      'Give someone a sensual back massage using lotion/oil (if available/consensual). Or drink twice.',
      'Let someone gently caress your "sensitive spots" (e.g., neck, inner elbow - CONSENT REQUIRED) for 30 seconds. Or drink.',
      'Take a body shot off someone (CONSENT REQUIRED). Or drink three times.',
      'Kiss the person the group chooses (CONSENT REQUIRED). Or drink twice.',
      'Remove an item of clothing using only your teeth. Or drink.',
      'Let the group write something on your body with marker (non-permanent). Or drink.',
      'Swap one item of clothing with someone of the opposite gender for the next 3 rounds. Or drink.',
    ],
  ),
]; 

// Function to get prompts for a specific game mode ID
List<String> getPromptsForMode(String modeId) {
  final mode = gameModes.firstWhere(
    (m) => m.id == modeId,
    orElse: () => GameMode(
      id: 'error',
      name: 'Error',
      description: 'Mode not found',
      icon: '❓',
      isPremium: false,
      samplePrompts: ['Error: Could not find prompts for mode ID: $modeId'],
      category: 'Error',
    ),
  );
  return List<String>.from(mode.samplePrompts); // Return a copy
}

// Function to get all prompts for selected modes
List<String> getPromptsForSelectedModes(List<GameMode> selectedModes) {
  List<String> allPrompts = [];
  for (var mode in selectedModes) {
    allPrompts.addAll(getPromptsForMode(mode.id));
  }
  // Optional: Shuffle the combined list if desired
  // allPrompts.shuffle(); 
  return allPrompts;
} 