class GameMode {
  final String id;
  final String name;
  final String description;
  final String icon;
  final bool isPremium;
  final List<String> samplePrompts;
  final String category;
  bool isSelected;

  GameMode({
    required this.id,
    required this.name,
    required this.description,
    required this.icon,
    required this.isPremium,
    required this.samplePrompts,
    required this.category,
    this.isSelected = false,
  });
}

final List<GameMode> gameModes = [
  // Free Modes
  GameMode(
    id: 'getting_started',
    name: 'Getting Started',
    description: 'Perfect for warming up the party with simple drinking rules and challenges.',
    icon: '🎮',
    isPremium: false,
    category: 'Warm-Up (Free)',
    samplePrompts: [
      'Sip or Spill: If you\'ve ever slid into someone\'s DMs and regretted it',
      'Sip or Spill: If you\'ve ever pretended to know a TikTok dance you didn\'t',
      'Sip or Spill: If you\'ve ever worn the same clothes for multiple days in a row',
      'Sip or Spill: If you\'ve ever faked being sick to avoid a social obligation',
      'Sip or Spill: If you\'ve ever stalked an ex\'s new partner online',
      'Sip or Spill: If you\'ve ever lied about your age to get into a bar/club',
      'Sip or Spill: If you\'ve ever used a dating app just for validation',
      'Sip or Spill: If you\'ve ever taken a screenshot of someone\'s social media post without their knowledge',
      'Sip or Spill: If you\'ve ever accidentally liked an old Instagram post',
      'Sip or Spill: If you\'ve ever pretended to be interested in someone\'s story',
      'Last person to touch their nose drinks',
      'Current player, choose someone to take a drink with you',
      'Everyone wearing jeans drinks',
      'Current player and another player must play rock, paper, scissors. Loser drinks!',
      'Last person to stand up drinks',
      'Current player, give out drinks equal to your age',
      'Everyone who\'s been on a date this month drinks',
      'Everyone with a pet drinks',
      'Current player and another player must do a dance-off. Loser drinks!',
      'Last person to check their phone drinks',
      'Everyone who\'s traveled abroad drinks',
      'Current player, give 3 drinks to someone who makes you laugh',
      'Everyone wearing black drinks',
      'Last person to say "cheers" drinks',
      'Current player, choose someone to do a shot with',
      'Everyone who\'s been to a concert drinks',
      'Current player and another player must tell a joke. Worst joke drinks!',
      'Last person to touch their drink drinks',
      'Everyone who\'s been to college drinks',
      'Current player, give drinks to people who make you smile',
      'Everyone wearing sneakers drinks',
      'Last person to say "I love you" drinks',
      'Current player, choose someone to do a dance with',
      'Everyone who\'s been in a car accident drinks',
      'Current player and another player must sing a song. Worst singer drinks!',
      'Last person to laugh drinks',
      'Everyone who\'s been to a wedding drinks',
      'Current player, give drinks to people who make you happy',
      'Everyone wearing a watch drinks',
      'Last person to say "thank you" drinks',
      'Current player, choose someone to do a shot with',
      'Everyone who\'s been to a funeral drinks',
      'Current player and another player must tell a story. Worst story drinks!',
      'Last person to touch their face drinks',
      'Everyone who\'s been to a party drinks',
      'Current player, give drinks to people who make you laugh',
      'Everyone wearing a ring drinks',
    ],
  ),
  GameMode(
    id: 'getting_tipsy',
    name: 'Getting Tipsy',
    description: 'Step it up a notch with more challenging and entertaining drinking tasks.',
    icon: '🍻',
    isPremium: false,
    category: 'Warm-Up (Free)',
    samplePrompts: [
      'Current player, if you\'ve ever been caught in a lie, give out 3 drinks',
      'Everyone who\'s been late today drinks',
      'Current player gives out drinks equal to their siblings',
      'Current player and another player must play rock, paper, scissors. Loser drinks!',
      'Current player, if you got ghosted after a date, give out 2 drinks',
      'Current player, if you\'ve ever cheated on a test, take 2 drinks',
      'Everyone who\'s been to a club drinks',
      'Current player and another player must do a dance-off. Loser drinks!',
      'Current player, if you\'ve ever been fired, take 3 drinks',
      'Everyone who\'s been to a bar drinks',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must tell a joke. Worst joke drinks!',
      'Current player, if you\'ve ever been in a fight, take 2 drinks',
      'Everyone who\'s been to a concert drinks',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must sing a song. Worst singer drinks!',
      'Current player, if you\'ve ever been arrested, take 3 drinks',
      'Everyone who\'s been to a wedding drinks',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story. Worst story drinks!',
      'Current player, if you\'ve ever been in a car accident, take 2 drinks',
      'Everyone who\'s been to a funeral drinks',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, if you\'ve ever been in a long-distance relationship, take 2 drinks',
      'Everyone who\'s been to college drinks',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, if you\'ve ever had a one-night stand, take a drink',
      'Everyone who\'s been to a party drinks',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, if you\'ve ever been in a threesome, take a drink',
      'Everyone who\'s been to a bar drinks',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, if you\'ve ever been in a fight, take 2 drinks',
      'Everyone who\'s been to a concert drinks',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, if you\'ve ever been arrested, take 3 drinks',
      'Everyone who\'s been to a wedding drinks',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, if you\'ve ever been in a car accident, take 2 drinks',
      'Everyone who\'s been to a funeral drinks',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, if you\'ve ever been in a long-distance relationship, take 2 drinks',
      'Everyone who\'s been to college drinks',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
    ],
  ),

  // Premium Modes
  GameMode(
    id: 'never_have_i_ever',
    name: 'Never Have I Ever',
    description: 'Classic drinking game with a twist! Reveal secrets and drink to what you\'ve done.',
    icon: '🤔',
    isPremium: true,
    category: 'Classics',
    samplePrompts: [
      'Never have I ever used someone else\'s streaming account',
      'Never have I ever regifted a present',
      'Never have I ever pretended to be someone else online',
      'Never have I ever sneaked food into a movie theater',
      'Never have I ever gone a week without showering',
      'Never have I ever lied about my age on a dating app',
      'Never have I ever drunk dialed someone',
      'Never have I ever had a wardrobe malfunction',
      'Never have I ever slept through an important event',
      'Never have I ever broken something and blamed someone else',
      'Never have I ever sent a text to the wrong person',
      'Never have I ever gone skinny dipping',
      'Never have I ever faked being sick to skip work',
      'Never have I ever cheated on a test',
      'Never have I ever been arrested',
      'Never have I ever been in a fight',
      'Never have I ever been fired',
      'Never have I ever been to a club',
      'Never have I ever been to a bar',
      'Never have I ever been to a concert',
      'Never have I ever been to a wedding',
      'Never have I ever been to a funeral',
      'Never have I ever been to college',
      'Never have I ever been to a party',
      'Never have I ever been late to work',
      'Never have I ever ghosted someone',
      'Never have I ever had a crush on someone in this room',
      'Never have I ever been in a long-distance relationship',
      'Never have I ever had a one-night stand',
      'Never have I ever been in a threesome',
      'Never have I ever been in a car accident',
      'Never have I ever been in a fight',
      'Never have I ever been arrested',
      'Never have I ever been to a wedding',
      'Never have I ever been to a funeral',
      'Never have I ever been to college',
      'Never have I ever been to a party',
      'Never have I ever been to a bar',
      'Never have I ever been to a concert',
      'Never have I ever been to a wedding',
      'Never have I ever been to a funeral',
      'Never have I ever been to college',
      'Never have I ever been to a party',
    ],
  ),
  GameMode(
    id: 'most_likely_to',
    name: 'Most Likely To',
    description: 'Find out what your friends really think about who would most likely do what!',
    icon: '👀',
    isPremium: true,
    category: 'Classics',
    samplePrompts: [
      'Most likely to become a meme',
      'Most likely to win an eating contest',
      'Most likely to get arrested (for something minor)',
      'Most likely to become a TikTok star',
      'Most likely to invent something world-changing',
      'Most likely to survive a zombie apocalypse',
      'Most likely to write a bestselling novel',
      'Most likely to date a celebrity',
      'Most likely to go viral for something embarrassing',
      'Most likely to live off the grid',
      'Most likely to become a millionaire',
      'Most likely to move abroad',
      'Most likely to become famous',
      'Most likely to get married first',
      'Most likely to win the lottery',
      'Most likely to become a doctor',
      'Most likely to become a lawyer',
      'Most likely to become a teacher',
      'Most likely to become a chef',
      'Most likely to become a musician',
      'Most likely to become a writer',
      'Most likely to become an artist',
      'Most likely to become a scientist',
      'Most likely to become a politician',
      'Most likely to become a model',
      'Most likely to become an actor',
      'Most likely to become a dancer',
      'Most likely to become a singer',
      'Most likely to become a comedian',
      'Most likely to become a photographer',
      'Most likely to become a designer',
      'Most likely to become a programmer',
      'Most likely to become a gamer',
      'Most likely to become a chef',
      'Most likely to become a musician',
      'Most likely to become a writer',
      'Most likely to become an artist',
      'Most likely to become a scientist',
      'Most likely to become a politician',
      'Most likely to become a model',
      'Most likely to become an actor',
      'Most likely to become a dancer',
      'Most likely to become a singer',
      'Most likely to become a comedian',
      'Most likely to become a photographer',
      'Most likely to become a designer',
      'Most likely to become a programmer',
      'Most likely to become a gamer',
    ],
  ),
  GameMode(
    id: 'couples_night',
    name: 'Couples Night',
    description: 'Perfect for date night or couples party with romantic and fun challenges.',
    icon: '❤️',
    isPremium: true,
    category: 'Special Occasions',
    samplePrompts: [
      'Give your partner a gentle kiss',
      'Hold your partner\'s hand and look into their eyes',
      'Give your partner a warm hug',
      'Tell your partner what you love about them',
      'Give your partner a gentle massage',
      'Hold your partner close and slow dance',
      'Give your partner a sweet kiss on the cheek',
      'Tell your partner a romantic story',
      'Give your partner a gentle back rub',
      'Hold your partner\'s hand and walk together',
      'Give your partner a gentle kiss',
      'Hold your partner\'s hand and look into their eyes',
      'Give your partner a warm hug',
      'Tell your partner what you love about them',
      'Give your partner a gentle massage',
      'Hold your partner close and slow dance',
      'Give your partner a sweet kiss on the cheek',
      'Tell your partner a romantic story',
      'Give your partner a gentle back rub',
      'Hold your partner\'s hand and walk together',
      'Give your partner a gentle kiss',
      'Hold your partner\'s hand and look into their eyes',
      'Give your partner a warm hug',
      'Tell your partner what you love about them',
      'Give your partner a gentle massage',
      'Hold your partner close and slow dance',
      'Give your partner a sweet kiss on the cheek',
      'Tell your partner a romantic story',
      'Give your partner a gentle back rub',
      'Hold your partner\'s hand and walk together',
      'Give your partner a gentle kiss',
      'Hold your partner\'s hand and look into their eyes',
      'Give your partner a warm hug',
      'Tell your partner what you love about them',
      'Give your partner a gentle massage',
      'Hold your partner close and slow dance',
      'Give your partner a sweet kiss on the cheek',
      'Tell your partner a romantic story',
      'Give your partner a gentle back rub',
      'Hold your partner\'s hand and walk together',
      'Give your partner a gentle kiss',
      'Hold your partner\'s hand and look into their eyes',
      'Give your partner a warm hug',
      'Tell your partner what you love about them',
      'Give your partner a gentle massage',
      'Hold your partner close and slow dance',
      'Give your partner a sweet kiss on the cheek',
      'Tell your partner a romantic story',
      'Give your partner a gentle back rub',
      'Hold your partner\'s hand and walk together',
    ],
  ),
  GameMode(
    id: 'girls_night',
    name: 'Girls Night',
    description: 'Ultimate girls night out edition with female-focused fun and challenges.',
    icon: '👯‍♀️',
    isPremium: true,
    category: 'Special Occasions',
    samplePrompts: [
      'Share your worst first date story',
      'What\'s the most embarrassing thing you\'ve ever done in front of a crush?',
      'What\'s the weirdest text you\'ve ever received?',
      'What\'s your biggest dating dealbreaker?',
      'What\'s the most romantic thing a guy has ever done for you?',
      'Drink if you\'ve ever borrowed clothes without asking',
      'Take a sip if you\'ve cried watching a romance movie',
      'Everyone wearing makeup drinks',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  GameMode(
    id: 'boys_night',
    name: 'Boys Night',
    description: 'Bros night out challenges designed for the guys to have a great time.',
    icon: '🤜🤛',
    isPremium: true,
    category: 'Special Occasions',
    samplePrompts: [
      'What\'s the most embarrassing thing you\'ve ever done to try and impress a girl?',
      'What\'s your biggest fear in a relationship?',
      'What\'s the weirdest pick-up line you\'ve ever used?',
      'What\'s your biggest dating pet peeve?',
      'What\'s the most romantic thing you\'ve ever done?',
      'Drink if you\'ve ever tried to impress someone at the gym',
      'Take a shot if you\'ve lost in FIFA today',
      'Everyone with a beard drinks twice',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  GameMode(
    id: 'truth_or_drink',
    name: 'Truth or Drink',
    description: 'Answer truthfully to personal questions or take a drink to avoid answering!',
    icon: '🤫',
    isPremium: true,
    category: 'Classics',
    samplePrompts: [
      'What\'s your biggest regret or take a drink',
      'Reveal your last DM or drink twice',
      'Share your most embarrassing moment or finish your drink',
      'Current player, if you\'ve ever cheated on your partner, take 2 drinks',
      'Everyone who\'s been in a long-distance relationship drinks',
    ],
  ),
  GameMode(
    id: 'party_challenges',
    name: 'Party Challenges',
    description: 'Exciting physical and mental challenges to spice up the night and get everyone involved.',
    icon: '🎉',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Try to fit your whole fist in your mouth',
      'Sing a song in a different language (or make one up)',
      'Eat a spoonful of something spicy',
      'Give someone a piggyback ride around the room',
      'Do a handstand against the wall',
      'Try to lick your elbow',
      'Say the alphabet backward',
      'Hold an ice cube in your hand until it melts',
      'Stand on one leg for 30 seconds',
      'Do a cartwheel (or attempt one)',
      'Challenge someone to a dance-off or drink',
      'Do your best celebrity impression or take two drinks',
      'Make everyone laugh or finish your drink',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  GameMode(
    id: 'wildcards',
    name: 'Wildcards',
    description: 'Expect the unexpected with these random and surprising game-changing challenges.',
    icon: '🃏',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Everyone takes a shot',
      'Pick someone to skip their next turn',
      'Reverse the order of play',
      'The person to your left drinks',
      'The person to your right drinks',
      'Waterfall: Everyone drinks until the person who picked the card stops',
      'Thumb Master: Last person to put their thumb on the table drinks',
      'Make a Rule: Invent a new rule that everyone must follow for the rest of the game',
      'Categories: Choose a category and go around the circle naming things in that category. First person to repeat or hesitate drinks',
      'Rhyme Time: Say a word. The next person has to say a word that rhymes. Continue until someone can\'t think of a rhyme',
      'Switch drinks with the person to your right',
      'Everyone trades seats and drinks',
      'Create a new rule for the game',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  
  // Flirty Fun mode in Classics category
  GameMode(
    id: 'flirty_fun',
    name: 'Flirty Fun',
    description: 'Playful questions and light challenges to create chemistry and break the ice.',
    icon: '💋',
    isPremium: true,
    category: 'Classics',
    samplePrompts: [
      'Compliment the person to your left on something other than their looks',
      'Describe your celebrity crush',
      'Share your biggest turn-off (in a dating context)',
      'Rate the attractiveness of a fictional character',
      'Tell a cheesy pick-up line',
      'Impersonate someone\'s dating profile picture',
      'Do your best seductive pose',
      'Whisper a compliment to the person on your right',
      'Have a staring contest with someone you find attractive',
      'Play "kiss, marry, kill" with fictional characters',
      'Current player, give a compliment to another player or take a drink',
      'Everyone votes on who has the best smile. Current player counts to 3!',
      'Current player, share your best pickup line or take two drinks',
      'Current player, if you\'ve ever had a crush on someone in this room, take a drink',
      'Truth: Current player, who in this room would you go on a date with?',
      'Current player, make eye contact with another player for 10 seconds or drink',
      'Everyone who\'s been on a date this month drinks',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  
  // Heat It Up mode in Challenges category
  GameMode(
    id: 'heat_it_up',
    name: 'Heat It Up',
    description: 'More daring challenges that push comfort zones and increase intimacy.',
    icon: '🔥',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Never have I ever fantasized about someone in this room',
      'Most likely to have a secret admirer',
      'What\'s the most attractive quality in a person?',
      'Act out a suggestive word or phrase (keep it PG-13)',
      'Two players exchange increasingly flirty compliments',
      'Everyone anonymously writes down their favorite body part on themselves. Read them aloud and guess who wrote what',
      'Set up a "kissing booth" (a designated chair). Anyone can choose to go in for a kiss on the cheek from anyone else (with clear consent)',
      'Truth or Dare: Truths and dares with a flirty/suggestive theme, but nothing explicit',
      'Would you rather go on a date with [person 1] or [person 2]?',
      'Anonymously rate someone\'s outfit on a scale of 1-10',
      'Current player, whisper something in another player\'s ear that would make them blush',
      'Current player, take a body shot off of another player or take three drinks',
      'Everyone votes on who\'s the most seductive. Current player counts to 3!',
      'Current player, demonstrate your best dance move or finish your drink',
      'Current player, share a secret fantasy or take two drinks',
      'Current player and another player must hold hands until the next round',
      'Everyone who\'s kissed someone in the last week drinks',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  
  // No Limits mode in Challenges category
  GameMode(
    id: 'no_limits',
    name: 'No Limits',
    description: 'The most provocative and intimate category for those looking to push boundaries.',
    icon: '🌶️',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Never have I ever had a threesome',
      'What\'s your wildest sexual fantasy?',
      'Most likely to join OnlyFans',
      'Write down an anonymous sexual confession (within legal and ethical boundaries). Read them aloud and try to guess who wrote what',
      'Start a story with a sexually suggestive sentence (within legal and ethical boundaries). Each person adds a sentence',
      'Act out a consensual sexual scenario (within legal and ethical boundaries)',
      'Truth or Dare: Truths and dares with an explicit sexual theme (within legal and ethical boundaries, and with enthusiastic consent)',
      'Would you rather [explicit sexual scenario 1] or [explicit sexual scenario 2]?',
      'Like a fantasy football draft, but with sexual fantasies (within legal and ethical boundaries)',
      'Fill in the blanks to create a funny and erotic story (within legal and ethical boundaries)',
      'Write down your wildest fantasy anonymously. Everyone tries to guess who wrote what',
      'Strip down to your underwear and do a sexy dance for everyone',
      'Give someone a sensual massage for 30 seconds',
      'Let someone kiss your neck for 30 seconds',
      'Give someone a lap dance for 30 seconds',
      'Strip tease for the group',
      'Let someone caress your body for 30 seconds',
      'Give someone a sensual foot massage',
      'Let someone kiss your inner thighs',
      'Give someone a sensual back massage',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a story',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
      'Current player, give drinks to people who make you smile',
      'Current player and another player must do a dance together',
      'Current player, give drinks to people who make you happy',
      'Current player and another player must tell a secret',
      'Current player, give drinks to people who make you laugh',
      'Current player and another player must do a shot together',
    ],
  ),
  GameMode(
    id: 'wild',
    name: 'Wild',
    description: 'Adventurous challenges that push boundaries while keeping it fun and consensual.',
    icon: '🐯',
    isPremium: true,
    category: 'Challenges',
    samplePrompts: [
      'Strip down to your underwear and dance',
      'Give someone a lap dance',
      'Let someone kiss your neck',
      'Give someone a sensual massage',
      'Let someone caress your body',
      'Strip tease for the group',
      'Give someone a sensual foot massage',
      'Let someone kiss your inner thighs',
      'Give someone a sensual back massage',
      'Let someone caress your sensitive spots',
      'Strip down to your underwear and dance',
      'Give someone a lap dance',
      'Let someone kiss your neck',
      'Give someone a sensual massage',
      'Let someone caress your body',
      'Strip tease for the group',
      'Give someone a sensual foot massage',
      'Let someone kiss your inner thighs',
      'Give someone a sensual back massage',
      'Let someone caress your sensitive spots',
      'Strip down to your underwear and dance',
      'Give someone a lap dance',
      'Let someone kiss your neck',
      'Give someone a sensual massage',
      'Let someone caress your body',
      'Strip tease for the group',
      'Give someone a sensual foot massage',
      'Let someone kiss your inner thighs',
      'Give someone a sensual back massage',
      'Let someone caress your sensitive spots',
      'Strip down to your underwear and dance',
      'Give someone a lap dance',
      'Let someone kiss your neck',
      'Give someone a sensual massage',
      'Let someone caress your body',
      'Strip tease for the group',
      'Give someone a sensual foot massage',
      'Let someone kiss your inner thighs',
      'Give someone a sensual back massage',
      'Let someone caress your sensitive spots',
      'Strip down to your underwear and dance',
      'Give someone a lap dance',
      'Let someone kiss your neck',
      'Give someone a sensual massage',
      'Let someone caress your body',
      'Strip tease for the group',
      'Give someone a sensual foot massage',
      'Let someone kiss your inner thighs',
      'Give someone a sensual back massage',
      'Let someone caress your sensitive spots',
    ],
  ),
]; 